### ISSUE TITLE
[Bug] Failed to build from source code

### ISSUE THREAD

**Issue by hajsf** [codenotary/immudb#1121]
At my device running windows 11, I failed to build immudb from source code, getting the below error:

```bach
PS D:\Development\immudb-1> make immudb-static
process_begin: CreateProcess(NULL, date +%s, ...) failed.
env -u GOOS -u GOARCH go generate  ./webconsole
process_begin: CreateProcess(NULL, env -u GOOS -u GOARCH go generate ./webconsole, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [webconsole] Error 2
```

<img width="984" alt="image" src="https://user-images.githubusercontent.com/98168280/153704316-074547ac-7d0e-419c-b58a-cb90c022d83a.png">

**Comment by tomekkolo** [comment]
Hi @hajsf,

I see that you are using make for windows. The current Makefile is to be used in Linux environments. It uses /bash/shell to call various commands, and also bash syntax in other places. 
For example, error you see is because in windows cmd.exe there is no "env" command. 
You can still compile on windows, using i.e. WSL or by directly running go build commands. 

Hope this helps.

**Comment by hajsf** [comment]
> by directly running go build commands

I got `build constraints exclude all Go files`

<img width="1074" alt="image" src="https://user-images.githubusercontent.com/98168280/178074793-9a1ac09f-d2ea-4dd0-8913-457a765e3d1b.png">
