### ISSUE TITLE
[Feat] synchronous replication

### ISSUE THREAD

**Issue by tomekkolo** [codenotary/immudb#1341]
Synchronous replication data from master to slaves.
On commit master sends transactions to replicas and waits for confirmation before finishing the commit.
- [ ] Exportation part
- [ ] Replication part

**Comment by byo** [comment]
As agreed for 1.4 version - we need to implement a simplified version of the synchronous replication.

The main goal is: the client performing a write operation should get the confirmation of that write only once both master and some replicas has already persisted the change (what number of replicas made the confirmation should be configurable on the master). We could also go for a simplified version for now, so that the master doesn't have information what replicas are out there but instead keeps a dynamic state information from confirmations send from replicas.

**Comment by tomekkolo** [comment]
To implement:
- discarding pre-commit in replicator if there is a mismatch with master
- check the behavior of commits with conditions
- integration tests
- bugfixing and testing. Happy scenario can start to be e2e tested, but crash scenario are not ready yet.

**Comment by tomekkolo** [comment]
still to do:
- key not found bug
- propagatin context and having timeout 
- discard of transactions if cannot commit (due to timeout or other reason). Proper error handling (also for sdk)

**Comment by byo** [comment]
Medium priority: Issue found during tests:

```
immudb  2022/09/29 12:31:08 INFO: Replication error on database 'replicadb' from 'masterdb@localhost:45683' (2 consecutive failures). Reason: rpc error: code = Unknown desc = not logged in
immudb  2022/09/29 12:31:08 INFO: Replication error on database 'replicadb' from 'masterdb@localhost:45683' (2 consecutive failures). Reason: rpc error: code = Unknown desc = not logged in
immudb  2022/09/29 12:31:12 INFO: Replication error on database 'replicadb' from 'masterdb@localhost:45683' (3 consecutive failures). Reason: rpc error: code = Unknown desc = not logged in
immudb  2022/09/29 12:31:12 INFO: Replication error on database 'replicadb' from 'masterdb@localhost:45683' (3 consecutive failures). Reason: rpc error: code = Unknown desc = not logged in
```

After restarting primary, replicators on replicas try to use old authentication and do not catch errors. We could catch those errors properly to speed up recovery time.
