### ISSUE TITLE
Structured value

### ISSUE THREAD

**Issue by mmeloni** [codenotary/immudb#25]
There is currently no rule or protocol to manage meaningful data in the communication between immudb and clients.
This task aim to setup a first iteration to provide a structured value with 2 property: timestamp and payload setup by clients and managed by immudb.

Like other databases(ex mongodb) our strategy will be to setup structured values client side. This will be done inside our drivers(SDKs) or immugw.
This give us 3 advantages:
**1) immudb will remain simple. It will deal only with a raw bytestream as value. By this fact we will don't have to modify too much things inside the core**
**2) performance don't will decrease, memory usage will not increase. We don't have to open value to save timestamp serverside. In case somebody start to send us huge messages this will be a great advantage.**
**3) timestamp will be tamperproof because it's inserted inside value and it will be used to produce the hash for the merkletree**

**Main task**
To deal with raw structure server side we would like to use google.protobuf.Any as type of value inside KeyValue message

```
message KeyValue {
	bytes key = 1;
	bytes value = 2;
}
```
will be 
```
message KeyValue {
	bytes key = 1;
	google.protobuf.Any value = 2;
}
```

In another value.proto file we define the message structure

message StructuredValue {
	uint64 timestamp = 1
	bytes payload = 2;
}

After that you will have to do a small refactor inside immudb. The inner type of any is []Byte, so you shouldn't have any problems because the old value is of the same type.

**Client side**
Client side the implementation will be based on following pseudo code:
```
sv = new StructuredValue
sv.timestamp = getOsTimestamp
sv.payload = payloadByteArray
Any.pack(sv)
safesendObject = {
  "kv": {
    "key": "string",
    "value": sv
  },
  "rootIndex": {
    "index": "..."
  }
}
client.safeSend(safesendObject)
```

Please add a test that proofs that an element can be correctly deserialized serverside.
This is needed because we will need to deserialize messages in future tasks(auth, crypto Signatures, audit ecc... )

**Implementation in Immugw**
Immugw is an intelligent gateway in front of immudb. It make as a proxy but it simplify safeSet and safeGet calls providing autonomously the root index and, after retrieving data, it make all the verification needed in order to ensure that immudb is not been tampered. It can ran on the same machine in which the client is running, in a 3th machine between the client and immudb or just in the same machine of immudb(with a lower security).
We need to provide the timestamp generation inside immugw for safeset, set and batch set. The client which is consuming immugw safeSet endpoints is completly unaware of the generation.
In the safeget, get, scan and history methods the structured value has to be returned exploded in json.
Please provide unit tests and api tests on safeGet and safeSet methods.

**Implementation in immu client**
Same approch has to be done for immu client for method get, set, scan and history. Theese methods has to return timestamp in set scan and history and setup the structured value in set.

**Implementation in JS-SDK, Python-SDK, .Net-SDK and JAVA-SDK**
Please provide the same approch for safeSet and Get methods in our SDKs.
Provide also integration tests

**Useful tips.**

To rebuild schema.pb.go and schema.pb.gw.go:

```shell
make build/codegen
```

If you like to test easily immugw and immud take a look at this repo -> https://github.com/mmeloni/immudbdemo

Please use Conventional Commits -> feat(pkg/subPackage...):{commit message}

**Comment by nredko** [comment]
> The inner type of any is []Byte, so you shouldn't have any problems because the old value is of the same type.

@mmeloni , I think you're not correct: we have to implement separate marshalling of incoming data (for Set and SafeSet) in unstructured format `{bytes[] key, bytes[] value}`. If we'll use just autogenerated marshaller for new StructuredValue `{bytes[] key, protobuf.Any value}` then immugw will be able to receive only protobuf-prepared json in format 
```
{
    "Key": "KEY",
    "Value": {
         "TypeUrl": "googleApisAny", 
          "Value": "VALUE"
      }
}
```

So it is not just small refactoring, since

**Comment by mmeloni** [comment]
@nredko You are right. I was talking from an immudb point of view. Inside immugw methods's have to wrap complexity and let keep required only the strict necessary data.

**Comment by nredko** [comment]
We got very significant issue with this approach. `protobuf.any` is not suitable as replacement for `payload` byte array, since protobuf doesn't guarantee deterministic serialization: bytes array presenting `any` structure enveloping `StructuredValue`  can be serialized to different bytes arrays on different platforms, in different languages, different builds and even different runs of the same code. See https://github.com/protocolbuffers/protobuf/releases/tag/v3.0.0 - deterministic serialization requires special methods and is available only for C++.

We found this since we've got different results of hash function for `any` structures with same values. This makes such approach unusable.

So current proposal is to just append additional field `timestamp` to protocol, and implement our own serialization for compatibility with badger (i.e. first 8 bytes of badger's `value []bytes` will be deserialized as timestamp).

**Comment by nredko** [comment]
Probably more proper approach is to replace 'payload' type with structure `{timestamp, bytes}`

**Comment by mmeloni** [comment]
@nredko it's a pity that any doesn't work. However if we replace payload type and we will still be able to manage value without refactorize immudb core should not be a problem. 
I mean that I think we will able to manage value without unmarshal on immudb side, except for the specifics cases that we need to open the payload. Whats your idea?

**Comment by nredko** [comment]
@mmeloni If we change only `KeyValue` (transport structure) but leave `Item` (db structure) as is (bytestream as value) - we can use our own (very simple) serialization between transport and db, so it will not affect any `budger` data - so we will not get any decrease in performance.

```
message KeyValue {
	bytes key = 1;
	Content value = 2;
}

message Content {
	uint64 timestamp = 1;
	bytes payload = 1;
}

message Index {
	uint64 index = 1;
}

message Item {
	bytes key = 1;
	bytes value = 2;
	uint64 index = 3;
}
```

**Comment by mmeloni** [comment]
Ok, 
only to be sure:
methods like:
```
func (s *ImmuServer) Set(ctx context.Context, kv *schema.KeyValue) (*schema.Index, error) {
```
Will not change.
Only if we want to explore timestamp, for example,  we will need to unmarshal content.

**Comment by nredko** [comment]
In my understanding, there should be difference of models for server and for client. For now they all are messed and are used only according the set of required fields, not according layer of execution.

Server methods should use `Item` (probably with another structure without index like `NewItem`) and only client methods should use `KeyValue`.

```
message Index {
	uint64 index = 1;
}

message Item {
	bytes key = 1;
	bytes value = 2;
	uint64 index = 3;
}

message NewItem {
	bytes key = 1;
	bytes value = 2;
}
```
So that method should look like
```
func (s *ImmuServer) Set(ctx context.Context, ni *schema.NewItem) (*schema.Index, error) {
```
Otherwise we'll need to propagate serialization/deserialization down to server/database layer.

**Comment by nredko** [comment]
Well, I’m a bit overworked :)
Just replace ‘NewItem’ with ‘KeyValue’ and call my modified ‘KeyValue’ ‘StructuredValue’. 
In this case signature of server functions will not change in a char. 
```

**Comment by mmeloni** [comment]
Ok no problem Nik, thank you very much. When you are ready  could you please share a prototype with a working Set so we can make a tour?

**Comment by mmeloni** [comment]
@nredko Thank you very much.
@padurean please take a look and give us a feedback in case you see something wrong in order to merge your work on #40 when ready

**Comment by nredko** [comment]
Please note that GetSV and SetSV methods are not implemented in Server, so to implement SafeGet/SafeSet methods in any client (gw, drivers - our tasks, CLI - your), the client should append timestamp to payload bytestream (see /pkg/client/convert.go)
