### ISSUE TITLE
immudb backup does not work on windows

### ISSUE THREAD

**Issue by vchain-us-mgmt** [codenotary/immudb#293]

**Comment by padurean** [comment]
The problem that i identified was when specifying the current dir - i.e. `.` or `.\` - as the db dir.
Since it doesn't make sense to backup the current working directory, i've added a check which forbids this and suggests the user to use a specific sub-directory; this is the user error message that it prints:
> cannot backup the current directory, please specify a subdirectory, for example ./db

@vchain-us-mgmt if you want to test before the fix gets into the `master` branch, please use the `fix/backup-current-dir` feature branch and let me know your opinion.
