### ISSUE TITLE
Extensive product documentation

### ISSUE THREAD

**Issue by vchain-us-mgmt** [codenotary/immudb#354]
Update the product documentation and readmes so that users know how to run the solution.

The online documentation is generated from the content on this repo:

https://github.com/codenotary/immudb.io/tree/master/src/docs

**Comment by devisions** [comment]
There is one typo on [Quickstart > Docker > Run immugw](https://docs.immudb.io/quickstart.html#run-immugw) page: env var name is `IMMUGW_IMMUDB_ADDRESS` instead of `IMMUGW_IMMUDB-ADDRESS`.

Actually, I've spent some time 'til I figured that out, especially that `immuclient` worked from the start, just `immugw` wasn't able to connect. Eventually, I ended up with a setup that considers:
- its own Docker network
- a persistent volume so that I can still play with the data after restarts or Docker cleanups
```
docker network create immudb_net
docker run -it -d -p 3322:3322 -p 9497:9497 -v immudb:/.immudb_data --name immudb --network immudb_net codenotary/immudb:latest
docker run -it -d -p 3323:3323 --name immugw --env IMMUGW_IMMUDB_ADDRESS=immudb --network immudb_net codenotary/immugw:latest
```

If you are not planning to change the format of these docs, but just to update them (according to this issue description), I could contribute with PRs, instead of commenting here.

**Comment by jeroiraz** [comment]
Good catch @devisions, please feel free to open a PR.
Thanks!

**Comment by devisions** [comment]
@jeroiraz Sure! Glad to help! Please see [this PR](https://github.com/codenotary/immudb.io/pull/33). As mentioned there, if HTMLs need to be built, just tell me. I didn't see any instructions/notes about this aspect.

**Comment by jeroiraz** [comment]
thanks @devisions. just merged your PR.
