### ISSUE TITLE
Any know Limitation

### ISSUE THREAD

**Issue by olekukonko** [codenotary/immudb#491]
Is there any know limitation or a maximum number of data that can be stored on a single instance?

**Comment by vchaindz** [comment]
we're aware of tens of millions entries in a single instance, but not of a clear limitation. The inclusion proof takes longer when storing many millions of entries. Of course, that depends on your application and how often you check the integrity of immudb and can be optimized.

**Comment by jeroiraz** [comment]
the current maximum number of entries is currently limited to 18446744073709551615 (64bits unsigned integer), because entries are uniquely numerated for ordering and merkle tree generation.
The underlying key-value store is BadgerDB, so limitations on it will be inherited as well, but we're aware it can be used to store terabytes of data.
