### ISSUE TITLE
review immudb product documentation

### ISSUE THREAD

**Issue by vchain-us-mgmt** [codenotary/immudb#493]
Check if documentation is complete and understandable

**Comment by devisions** [comment]
Hi!

I would like to contribute here as currently I am starting to evaluate it and thus playing with it. At the same time I am quite picky on the details and consistency, so here I am... 😊 starting with some initial feedback.

First, this issue's scope has already being addressed in issue [#472 Review product immudb product documentation](https://github.com/codenotary/immudb/issues/472), so you may want to close that one.

Second, in [How it works > Checking data consistency](https://docs.immudb.io/how-it-works.html#checking-data-consistency), the diagram needs small updates:
- The first statement related to "Client A", I would started with "Client A inserts ..." instead of "A client inserts ...", just to be specific.<br/>
  <img src="https://raw.githubusercontent.com/codenotary/immudb/master/img/immudb-consistency-diagram.png" width="300" target="_blank">

- At the bottom, in the middle it should be "Client B" instead of "Client A".

I could update the diagram if I have the _source_ of it or simply create a new and similar one.

<br/>
And thanks for this nice product! 😊

**Comment by jeroiraz** [comment]
Thanks @devisions for the detailed review and findings. I've just updated the diagram. Please feel free to make a new one, and we can include the source for collaborative updates.
