### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by schmurfy** [codenotary/immudb#552]
This is not really an issue but I don't know where to post this.
I wanted to give your challenge a try mainly because this is an intriguing database I wanted to play with but its current state is really frustrating and I doubt I will spent much more time on it:

- the documentation is incomplete and it is hard to find answers (for the go library at least)
- no transactions (or is it ?), I found a `SetBatch` method with no `Safe` variation, what does it do, does it do the verifications ? no clue
- the documentation talks about extending the schema but no real example and all methods take `key` and `value`  as input so I am not sure how you expect the client to extend the schema
- the reference system is barely documented: does fetching a key brings its references ? (it seems so looking at the code but not sure), it also looks like an afterthought with no way I can see to set references and values in the same transaction which seems like a reasonable thing to expect.

The challenge idea is nice even with no real prize but I expected at least a proper documentation and basic feature set to get me started.

**Comment by Giako** [comment]
Hi @schmurfy, thanks for your feedback on the documentation.
We are improving it as I'm writing and we will take into consideration the points that you brought as the next improvements.

Here are a couple of tips, in the meantime:

- transaction support is not yet ready, but it's on immudb roadmap. We have initial support for them via the `setBatch` call.

- `setBatch` does a bulk of set commands atomically (without verification to ensure better performance), but you can verify the correct insertion of untampered data by issuing a safeGet command on the last inserted key. This will make sure your client's and the server's roots are compatible, proving that all past values are not tampered with.

- setting both references and values in the same atomic operation is a feature that is currently being worked on. Right now, the client application can coordinate access to immudb using locking mechanisms to make sure both values and references are added.

We'll keep you posted on both docs update and Set key+reference method. Let us know if you find any other unclear parts in the immudb docs for us to improve.

**Comment by schmurfy** [comment]
Thanks for the clarifications, one thing that is was obvious to me is the real implications behind `Set` vs `SafeSet`, if I write data without verification does that mean I can work on a corrupted/modified database without knowing ?
If that's the case why is it allowed ?

**Comment by mmeloni** [comment]
Writing data is the same both in Set and SafeSet. The only difference is that safeSet returns to the client proofs needed to matematecally verify that the data si really wrote correctly.
If you never check the proofs the scenario you mention is possible.
This is allowed because generating proofs slightly impact on performances, so we allow also set and get primitives without proofs. It is still possible get the proofs for a specific item at any time, so the decison on the frequency checks it's completely up to the final users.
It's possible also to use dedicated auditors to ensure the db consistency, but the fact that every client is also an auditor is an interesting solution.

**Comment by jeroiraz** [comment]
Hi @schmurfy, we appreciate your feedback.

We're already improving the documentation and also revising the Golang SDK.

Meanwhile, I'd like to share a minimalist yet illustrative sample on how to provide a document-like data model on top of immudb key-value data model.

I'm defining a mapping using the client SDK, which becomes feasible due to atomic multi-key insertion support, and as mentioned in one of the comments above, multi-key insertion will also support references with "read your own writes" semantics, but probably it's a feature not needed, at least for the scope of the challenge.

Caveat: I'm using SetAll method as implemented in immudb4j, which receives a list of key-value pairs instead of a BatchRequest, which is a bit more complex to build. We're revising this, but I wanted to provide some hints on how to solve the challenge.

Please do not hesitate to reach us out on slack.

```
dummyDocs := []struct {
		id     int
		title  string
		body   []byte
		parent int
	}{
		{
			12,
			"dummy title",
			[]byte("dummy body"),
			-1,
		},
		{
			123,
			"dummy title",
			[]byte("dummy body"),
			12,
		},
	}

	for i := 0; i < len(dummyDocs); i++ {
		m := make(map[string][]byte, 3)

		// doc_ID_title
		m[fmt.Sprintf("doc_%d_title", dummyDocs[i].id)] = []byte(dummyDocs[i].title)

		// doc_ID_body
		m[fmt.Sprintf("doc_%d_body", dummyDocs[i].id)] = dummyDocs[i].body

		if dummyDocs[i].parent >= 0 {
			// doc_ID_parent
			var b [4]byte
			binary.BigEndian.PutUint32(b[:], uint32(dummyDocs[i].parent))
			m[fmt.Sprintf("doc_%d_parent", dummyDocs[i].id)] = b[:]
		}

		kvList := &schema.KVList{KVs: nil}

		for k, v := range m {
			kvList.KVs = append(kvList.KVs, &schema.KeyValue{Key: []byte(k), Value: v})
		}

		_, err = client.SetAll(ctx, kvList)
	}

	for i := 0; i < len(dummyDocs); i++ {
		i, _ := client.SafeGet(ctx, []byte(fmt.Sprintf("doc_%d_title", dummyDocs[i].id)))

		fmt.Printf("%s: %s\n", i.Key, i.Value)
	}
```

**Comment by schmurfy** [comment]
thanks :)
