### ISSUE TITLE
Single or multiple collection

### ISSUE THREAD

**Issue by hajsf** [codenotary/immudb#721]
I understood there is an option for multiple databases, but didn't get how it is handling collections, if I have 2 collections, one for 'purchase orders' and one for 'shipments' how can I ask the shop to sauce in the correct collection. I couldn't see anything at the [Get and Set](https://docs.immudb.io/master/sdk.html#get-and-set)

**Comment by mmeloni** [comment]
Hu @hajsf,
you can create and select different databases before start to writing data inside immudb, [here](https://docs.immudb.io/master/sdk.html#multiple-databases) you will find more informations.

We have also [secondary indexes](https://docs.immudb.io/master/sdk.html#secondary-indexes) that can be used to handle collections.

If you prefer we have also a [discord channel](https://discord.com/invite/ThSJxNEHhZ) in order to receive quick help.

**Comment by hajsf** [comment]
Thanks
