### ISSUE TITLE
building immudb on openSuSE Leap 15.1 on Intel x86-64 problem

### ISSUE THREAD

**Issue by vmdave9** [codenotary/immudb#758]
**What happened**
This error was reported:
build github.com/codenotary/immudb/cmd/immudb: cannot find module for path crypto/ed25519
make: *** [Makefile:74: immudb-static] Error 1

**What you expected to happen**
The build to complete with no errors

**How to reproduce it (as minimally and precisely as possible)**
download latest version of immudb (immudb-0.9.2)
cd immudb-0.9.2
make immudb-static

**Environment**
```shell
h/w: Intel x86-64
s/w: openSuSE Leap 15.1
go: go version go1.11.13 linux/amd64

# run "immu* version" and copy/paste the output here
n/a 

**Additional info (any other context about the problem)**
Since I am very new to the to the go language and it's build processes, I was trying to build immudb here on Linux before I attempt to build it on the IBM z/OS USS platform.
Many thanks.
DJ

**Comment by dmacvicar** [comment]
Hi @vmdave9

As you can see from go.mod, we require go 1.13.

I see at [Leap 15.1 has go1.13 in the Update repository](https://build.opensuse.org/project/show/openSUSE:Leap:15.1:Update).

Make sure you have the update repository enabled, then do:

```
sudo zypper in go1.16
sudo update-alternatives --set go /usr/lib64/go/1.16/bin/go
```

And that should fix your problem. Reopen if it does not!

Note: openSUSE Leap is already End-of-Life since Feb 2nd 2021.
