### ISSUE TITLE
Soft delete

### ISSUE THREAD

**Issue by zaza81** [codenotary/immudb#946]
**What would you like to be added or enhanced**

User should be able to perform deletion as in SQL standard 

**Why is this needed**
immugorm

**Additional context**

It's not a standard delete as we are dealing with immutability, the data should be in db  but it's not being retrieved with simple read queries - also some work on indexing is needed.

**Comment by lonnietc** [comment]
Hello All,

Just came across immudb and have been playing with it a bit, which I must say, is fantastic.

I am interested if some type of "soft" DELETE sql statement will be added and also on this topic what about some type of DROP table which could both be challenging for an immutable database?

Any thoughts would be greatly appreciated.

**Comment by jeroiraz** [comment]
Hi @lonnietc, great to hear that.

There is an open PR with logical deletion in SQL (https://github.com/codenotary/immudb/pull/990)

It'd be great if you can build immudb from that branch and check if everything works as you would expect

**Comment by lonnietc** [comment]
Hello @jeroiraz,

Thanks for the quick response and I will give it a try, but have one dumb question here. A bit new to some things and I do not know how to pull that branch.

**Comment by lonnietc** [comment]
Sorry, but I may have just figured it out.

**Comment by lonnietc** [comment]
Hello,

I just compiled it up and did a simple test with:

DELETE FROM orders WHERE productid=5;

Got Error:

Syntax Error: Unexpected Identifier.

Used:
https://github.com/codenotary/immudb/tree/feat_sql_del

**Comment by jeroiraz** [comment]
hmm, are you using immuclient, the sdk or webconsole?
Please feel free to join our Discord channel, we can easily interact there as well

**Comment by lonnietc** [comment]
I did a fresh compile after downloading the zip instead of a git clone and it seems to have worked this time.

Strange, but working now.

Anyway, Thanks for the help and I will look into joining the Discord channel as well since I really am interested in peoples thoughts on the other question that I posted related to using a Golang P2P library to effectively had a blockchain of blockchains to connect remote nodes in a highly distributed Immudb project.

**Comment by lonnietc** [comment]
I have the Discord app installed but cannot seem to find an immudb channel.

Am I missing something?

**Comment by lonnietc** [comment]
Hello Again,

Since I am unable to locate the Discord channel (Maybe you have a link somewhere that you could provide), I wanted to extend the question of SQL "DROP and DELETE" actions and continuing along deletion in SQL (#990)

I am wondering if any changes have been implemented for:

=== Drop a Column from a Table
ALTER TABLE Customers DROP COLUMN ContactName;

=== Drop a Table from a Database
DROP TABLE table_name;

=== Drop a Database
DROP DATABASE DatabaseName;

I used the basic and general SQL that is presented from "SQL Tutorial" 

https://www.tutorialspoint.com/sql/index.htm

As it seems to be pretty generic although Immudb does see to want, or have, compatibility with PostgreSQL which is also a fine database by the way.

Any thoughts on these DROP and DELETE actions?

Thanks and have a great day

**Comment by jeroiraz** [comment]
Hi, discord channel (https://discord.gg/ThSJxNEHhZ) (the link it's in the readme as well)

ALTER and DROP are not yet supported

But `DELETE FROM` it's already merged into master and will be included in the next release

**Comment by lonnietc** [comment]
Thanks, I must have missed the discord link in the readme, sorry.

Will join now.
